Add  golangci-lint linter to the core Golang makefile.
make-files/pkg-go pull request #6
Opened 2021-04-24 23:22 UTC by danilvpetrov

This PR attempts to add the `golangci-lint` linter to the Golang makefile.

2021-04-25 22:54 UTC, jmalloc requested changes
Thanks man!

In addition to what I commented on inline, I think it'd be good to make sure that the linter only runs if the source files have actually changed.

We could accomplish this using a "touch file" that gets touched after the linting runs.  The touch file would be created by a recipe that depends on the Go source files. Here's an example from the JS makefiles: https://github.com/make-files/pkg-js/blob/5c0e8fd3130fa782a63a56ce3052f03acd1538e6/include/jest.mk#L59

2021-04-25 22:54 UTC, jmalloc commented on bin/.golangci.yml
> +    - govet
Are these two meant to be here? Based on the PR description I would have expected just the two SQL-related ones.

2021-04-25 22:54 UTC, jmalloc commented on bin/install-golangci-lint
> +# own go.mod. We ignore
I'm guessing this is just copied from something that I messed up, but the last sentence just trails off :P

2021-04-25 22:54 UTC, jmalloc commented on Makefile
> +	cp -f $(MF_ROOT)/pkg/go/v1/bin/.golangci.yml "$(MF_PROJECT_ROOT)/$(@D)"
If I am reading this correctly this will copy the config file to every project the first time it's run.  I think we should just use the config file bundled with the makefile. Otherwise we'll need to keep it in sync across every repo.

2021-04-25 23:49 UTC, danilvpetrov commented on bin/.golangci.yml
> +    - govet
Yeah, I did take those two from their default configuration from [here](https://golangci-lint.run/usage/configuration/). My thought was that they probably want to keep them in case something is changed in the default linter set. However, that does not make much sense anyway as we would probably want to always be in sync with the default linter set.

I am going to take those out.

2021-04-26 00:01 UTC, danilvpetrov commented on bin/install-golangci-lint
> +# own go.mod. We ignore
Yeah I copied it over from [here](https://github.com/make-files/pkg-protobuf/blob/v2/bin/install-protoc-gen-go#L19-L20). Yeah I did not realize that the comment was half-finished.

2021-04-26 00:03 UTC, danilvpetrov commented on Makefile
> +	cp -f $(MF_ROOT)/pkg/go/v1/bin/.golangci.yml "$(MF_PROJECT_ROOT)/$(@D)"
Ok that makes sense. Doing the changes now...

2021-04-26 00:19 UTC, danilvpetrov commented on Makefile
> +	cp -f $(MF_ROOT)/pkg/go/v1/bin/.golangci.yml "$(MF_PROJECT_ROOT)/$(@D)"
Should be fixed in https://github.com/make-files/pkg-go/pull/6/commits/3657c52c0490c177da19715991e25b5b996843f6.

2021-04-26 00:19 UTC, danilvpetrov commented on bin/install-golangci-lint
> +# own go.mod. We ignore
Should be fixed in https://github.com/make-files/pkg-go/pull/6/commits/c0759144cc6f14c5af377710c360da4f6e2d8049

2021-04-26 00:19 UTC, danilvpetrov commented on bin/.golangci.yml
> +    - govet
Should be fixed in https://github.com/make-files/pkg-go/pull/6/commits/d1addb8d802d61b5a0f56a4f0761c503e00bd375

2021-04-26 00:58 UTC, jmalloc requested changes
I can't seem to link to my previous review comment for some reason, but the only other thing is what I mentioned there:

> In addition to what I commented on inline, I think it'd be good to make sure that the linter only runs if the source files have actually changed.
>
> We could accomplish this using a "touch file" that gets touched after the linting runs. The touch file would be created by a recipe that depends on the Go source files. Here's an example from the JS makefiles: https://github.com/make-files/pkg-js/blob/5c0e8fd3130fa782a63a56ce3052f03acd1538e6/include/jest.mk#L59

2021-04-26 00:58 UTC, jmalloc commented on bin/.golangci.yml
> +linters:
This belongs in `etc/` not `bin/`

2021-04-26 09:26 UTC, danilvpetrov commented on bin/.golangci.yml
> +linters:
I would imaging that if we are to go with "touch file" approach we wouldn't need running the linter in the "precommit" target, right?

2021-04-26 10:20 UTC, danilvpetrov commented on bin/.golangci.yml
> +linters:
All of the comments above should be addressed in https://github.com/make-files/pkg-go/pull/6/commits/7a77f5301e2a345727a063e31f8371900075ab20. I left the "touch file" in the `precommit` target assuming you did not want to change it.

2021-04-26 22:24 UTC, jmalloc commented on bin/.golangci.yml
> +linters:
Yeah, that all looks right to me. I assume you've been trying this locally?  If so, go ahead and merge.

2021-04-27 00:08 UTC, danilvpetrov commented on bin/.golangci.yml
> +linters:
Yeah, local checks are complete: it works as expected.

2021-04-27 00:08 UTC, merged